    [tool.black]
    py38 = true
    line-length = 79
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | venv
      | env
      | \.pyc

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
    '''

    [tool.isort]
    multi_line_output = 3
    include_trailing_comma = true
    force_grid_wrap = 0
    use_parentheses = true
    ensure_newline_before_comments = true
    line_length = 79
